# Generated by Django 5.1.3 on 2025-03-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
