# Generated by Django 5.1.3 on 2025-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_gpu_tdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='ram_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
