# Generated by Django 5.1.3 on 2025-04-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_motherboard_ram_slots_motherboard_ram_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='speed',
            new_name='boost_clock',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='thread_count',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='vram_gb',
        ),
        migrations.AddField(
            model_name='case',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='core_clock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='graphics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='smt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpu',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='offers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
