# Generated by Django 5.1.3 on 2025-05-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_rename_speed_cpu_boost_clock_remove_cpu_thread_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='resolution',
        ),
    ]
