# Generated by Django 5.1.3 on 2025-05-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_remove_gpu_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='url',
        ),
        migrations.AlterField(
            model_name='cooler',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Cooler Type'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='boost_clock',
            field=models.FloatField(blank=True, null=True, verbose_name='Boost Clock (GHz)'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core_clock',
            field=models.FloatField(blank=True, null=True, verbose_name='Base Clock (GHz)'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core_count',
            field=models.IntegerField(verbose_name='Core Count'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='PassMark CPU Mark'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='graphics',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Integrated Graphics'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='smt',
            field=models.BooleanField(default=False, verbose_name='Simultaneous Multithreading (SMT)'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(max_length=100, verbose_name='Socket'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='tdp',
            field=models.IntegerField(blank=True, null=True, verbose_name='TDP (W)'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='thread_mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='PassMark Thread Mark'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='g2d_mark',
            field=models.FloatField(blank=True, null=True, verbose_name='PassMark 2D Mark'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='g3d_mark',
            field=models.FloatField(blank=True, null=True, verbose_name='PassMark G3D Mark'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.IntegerField(blank=True, null=True, verbose_name='TDP (W)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vram',
            field=models.IntegerField(verbose_name='VRAM (MB)'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RAM Slots'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RAM Type'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Form Factor'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(max_length=50, verbose_name='Socket'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='power',
            field=models.IntegerField(verbose_name='Wattage (W)'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Form Factor'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.IntegerField(verbose_name='Size (GB)'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(max_length=50, verbose_name='RAM Type'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='space',
            field=models.IntegerField(verbose_name='Capacity (GB)'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Storage Type'),
        ),
    ]
