# Generated by Django 5.1.3 on 2024-12-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=255)),
                ('cores', models.IntegerField()),
                ('cpu_mark', models.IntegerField()),
                ('thread_mark', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('socket', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_name', models.CharField(max_length=255)),
                ('g3d_mark', models.IntegerField()),
                ('g2d_mark', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('vram', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
