# Generated by Django 5.1.3 on 2024-12-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='tdp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
