# Generated by Django 5.1.3 on 2024-12-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cpu_tdp_alter_gpu_tdp_alter_gpu_vram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='thread_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
