# Generated by Django 5.1.3 on 2025-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pcbuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuild',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
