# Generated by Django 5.1.3 on 2025-03-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pcbuild_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcbuild',
            name='case',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='cooler',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='psu',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='pcbuild',
            name='storage',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Cooler',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
        migrations.DeleteModel(
            name='PSU',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='PCBuild',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
