# Generated by Django 5.1.3 on 2025-02-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cpu_options_alter_gpu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('disk_mark', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'HDD',
                'verbose_name_plural': 'HDDs',
            },
        ),
    ]
